// For now, we are going to use fetch, but eventually we will
// use axios. This is mainly for learning experience...

import type { UUID } from "crypto";
import type { LngLat } from "maplibre-gl";

export type UserRestaurant = {
    "user_restaurant_id": UUID,
    "name": string,
    "longitude": LngLat["lng"],   // number
    "latitude": LngLat["lat"],    // number
    "rating": number | null,
    "price_range": number | null,
    "descriptors": string[],
    "menu_items": string[],
    "notes": string
}

// Also for now, we are going to hardcode a localhost variable
// pointing to the db "server". We will implement a proper
// backend in the coming months. This "server" is generated by
// json-server, which depends on a db.json file (gitignored)
const SERVER_URL = "http://localhost:6789";

// Also for now, we are going to create a fake API with
// create, post, put, and delete functionality. 
export const UserRestaurantAPI = {
    get: async () => {

        try {
            const response = await fetch(`${SERVER_URL}/user/restaurants`, {
                method: 'GET',
                credentials: 'include'
            })
            if (!response.ok) {
                throw new Error(await response.json())
            }
            const json = await response.json();
            return json as UserRestaurant[];
        } catch (error) {
            if (error instanceof Error) console.error(error)
        }

        return [];
    },

    post: async (data: UserRestaurant) => {
        try {
            const response = await fetch(`${SERVER_URL}/user/restaurants`, {
                method: 'POST',
                credentials: 'include',
                headers: {'Content-Type': 'application/json'},
                body: JSON.stringify(data)
            })
            if (!response.ok) {
                throw new Error("Failed to Create Restaurant")
            }
        } catch (error) {
            if (error instanceof Error) console.error(error) 
        }

        return [];
    },

    put: async (data: UserRestaurant) => {
        try {
            const response = await fetch(`${SERVER_URL}/user/restaurants/${data.user_restaurant_id}`, {
                method: 'PUT',
                credentials: 'include',
                headers: {'Content-Type': 'application/json'},
                body: JSON.stringify(data)
            })
            if (!response.ok) {
                throw new Error("Failed to Update Restaurant")
            }
        } catch (error) {
            if (error instanceof Error) console.error(error)
        }

        return [];
    },

    delete: async (data: UserRestaurant) => {
        try {
            const response = await fetch(`${SERVER_URL}/user/restaurants/${data.user_restaurant_id}`, {
                method: 'DELETE',
                credentials: 'include'
            })
            if (!response.ok) {
                throw new Error("Failed to Delete Restaurant")
            }
        } catch (error) {
            if (error instanceof Error) console.error(error)
        }

        return [];
    }
}