// For now, we are going to use fetch, but eventually we will
// use axios. This is mainly for learning experience...

import type { UUID } from "crypto";
import type { LngLat } from "maplibre-gl";

// Also for now, we are going to hardcode a localhost variable
// pointing to the db "server". We will implement a proper
// backend in the coming months. This "server" is generated by
// json-server, which depends on a db.json file (gitignored)

const SERVER_URL = "http://localhost:3000";

type UserRestaurants = {
    "id": UUID,
    "name": string,
    "address": string,
    "longitude": LngLat["lng"],   // number
    "latitude": LngLat["lat"],    // number
    "rating": number,
    "price_range": number,
    "tags": string[],
    "notable_items": string[]
}[]

export async function getUserRestaurants(): Promise<UserRestaurants> {
    try {
        const response = await fetch(`${SERVER_URL}/restaurants`)
        if (!response.ok) {
            throw new Error("Failed to fetch")
        }
        const json = await response.json();
        return json as UserRestaurants;
    } catch (error) {
        if (error instanceof Error) console.error(error)
    }

    return [];
}