// For now, we are going to use fetch, but eventually we will
// use axios. This is mainly for learning experience...

// Also for now, we are going to hardcode a localhost variable
// pointing to the db "server". We will implement a proper
// backend in the coming months. This "server" is generated by
// json-server, which depends on a db.json file (gitignored)

const SERVER_URL = "http://localhost:3000";

export async function getUserRestaurants(): Promise<any> {
    try {
        const response = await fetch(`${SERVER_URL}/restaurants`)
        if (!response.ok) {
            throw new Error("Failed to fetch")
        }
        const json = await response.json();
        return json;
    } catch (error) {
        if (error instanceof Error) console.error(error.message)
    }
}